### ISSUE TITLE
DoubleRounderTest doesn't check expected and actual double values match

### ISSUE THREAD

**Issue by Overruler** [tools4j/decimal4j#10]
The [org.decimal4j.util.DoubleRounderTest](https://github.com/tools4j/decimal4j/blob/master/src/test/java/org/decimal4j/util/DoubleRounderTest.java#L117) class has a bug and can never fail. As a result ArithmeticResult class only asserts if thrown exceptions are different.

The cause of the bug is that the two ArithmeticResult instances that should compare expected and actual values are [both](https://github.com/tools4j/decimal4j/blob/master/src/test/java/org/decimal4j/util/DoubleRounderTest.java#L117) [created](https://github.com/tools4j/decimal4j/blob/master/src/test/java/org/decimal4j/util/DoubleRounderTest.java#L130) using the original double value rather than the rounded values the test calculates.

**Comment by terzerm** [comment]
Thanks for reporting --- good finding.

**Comment by terzerm** [comment]
Fixed with commit 6045df60424c42153475d79044f77f8d8a55e19b.
