### ISSUE TITLE
Kotlin Extensions

### ISSUE THREAD

**Issue by LouizFC** [tools4j/decimal4j#13]
I am using this lib in production for almost a year now. In the mean time I am transitioning most of the projects I am working on to Kotlin, gradually. 

I have some extensions to make this lib more friendly to kotlin [operator overloading](https://kotlinlang.org/docs/reference/operator-overloading.html), and I am planning to make the zero garbage syntax more friendly using [inline classes](https://kotlinlang.org/docs/reference/inline-classes.html) when they are released.

I could polish some of my code to make it public, but I am here to ask what approach should I take:

- Create a new repository or
- Submiting a PR here under a different module

Both approaches have the downside that I am clueless on how to publish artifacts to the Maven Central, but I could use this opportunity as a learning experience.

**Comment by terzerm** [comment]
Great to hear that you are using the library in production!

I would be interested to make decimal4j more Kotlin friendly.  I have personally no experience with Kotlin but would be interested to get a bit into it as well.

Not sure what the best structure is for this, probably modularising the project would make most sense.  So submitting a PR with a new module would be a good start.

Regarding maven central --- you need to own the domain to push to maven central.  So we would do that if we develop it under the current domain.  For your own projects you can find information on the web how to do it.  The first time is a bit painful but once that is done it is pretty straight forward.

**Comment by terzerm** [comment]
Closing as there is no further activity on this.
