### ISSUE TITLE
Question: Unsigned Values

### ISSUE THREAD

**Issue by A248** [tools4j/decimal4j#16]
I am making a program for a video game to handle player balances. Since balances can never be negative, I'm hoping to use unsigned values to maximise how large of a balance can be stored. Also, there are no ways to multiply or divide a balance, so that makes implementation easier.

Currently, my program uses zero-garbage computations, and I expose both the raw `long`s and the `DecimalArithmetic` used to manipulate them as part of the API. Ideally, dependents could use the DecimalArithmetic to convert "normal" numbers to internal numbers for interacting with the API, most commonly through the *fromXXX* methods which convert other number types to unscaled longs. However, using one of these methods will produce a long which is signed. How do I get a `DecimalArithmetic` specialised for unsigned values?

I found the Unsigned helper but it didn't seem to satisfy what I'm looking for. I know I could just implement `DecimalArithmetic` and delegate the *fromXXX* methods to the decimal4j implementation after converting signed numbers to unsigned. I was wondering if there was a cleaner solution.

**Comment by terzerm** [comment]
Firstly thanks for using the decimal4j library.

To your question a few comments:
- Java does not really have unsigned integers, hence defining an unsigned value and dealing with it is always going to be somewhat strange
- Decimal4j does not currently support unsigned decimals and is not planning to
- If you are not using multiplication and division, what would you use exactly that is not just a standard operation?  I can only think of the compare and conversion methods that are different.
- Are you really sure you need the extra numbers?  After all you safe only one bit from 64
- Looking at the DecimalArithmetics interface, only compare and from/to and trivial methods such as abs, signum would be different and the more complicated multiply/divide method that you are not using

Sorry if I cannot help you better but I am not fully understanding the reason you need unsigned support.  Hence it is a bit difficult to give good advice.

**Comment by A248** [comment]
I thought this over and I guess I do not need them after all. It's probably not worth it. Thank you though!
