### ISSUE TITLE
Using GitHub Discussions for Q&A

### ISSUE THREAD

**Issue by keilw** [tools4j/decimal4j#18]
Hi,
I heard about your library in the [JavaMoney](http://javamoney.org) project and also mentioned it in the Discussions formum of the [JSR 385 Reference Implementation](https://github.com/unitsofmeasurement/indriya/discussions). 

Where we use the new Discussion feature GitHub introduced a little while ago. I can't say how active this project still is, though it feels mature and claims to perform better than e.g. BigDecimal, so if you continue to discuss questions and suggestions maybe consider converting them to actual Q&A entries in a Discussion forum, you should be able to do that without much effort from an existing issue.

Regards,
Werner

**Comment by terzerm** [comment]
Hi Werner,

Thanks for your comments and interest in the library.

You are correct that there is not much activity in the project at the moment.  It was also correctly noted that the library is quite mature and I can confirm that it is successfully in operation at this moment in several productive applications.  Therefore it is not really necessary for decimal4j to have active development.  Note however that the project is still actively maintained and updated and we also react to reported issues and comments.

We are currently using the question label to classify issues as Q&A (see Q&A link on main page).  Thanks for your proposal to use the discussion forum instead --- I will consider this going forward.

Please let me know if I can help in the mentioned JSR 385 reference implementation or anywhere else --- I am more than happy to provide support if I can to help integrating decimal4j in another library or project.

Regards,
Marco

**Comment by keilw** [comment]
Marco, thanks for the update of what we also assumed to be the case.
Please feel free to watch or participate in https://github.com/unitsofmeasurement/indriya/discussions/328.
We have not even started any development tasks there but if we do, your input or support would be more than welcome.
