### ISSUE TITLE
Why are bitwise operators used in if checks?

### ISSUE THREAD

**Issue by v-chernyshev** [tools4j/decimal4j#22]
Hi, I've noticed that pretty much the whole library uses `&` and `|` instead of `&&` and `||` (see e.g. [this](https://github.com/tools4j/decimal4j/blob/a2f36d70c126f9b28b439e9e071f6ff956f06ac0/src/main/java/org/decimal4j/arithmetic/Mul.java#L88)  example). What is the reason behind it? Unlike logical operators, the bitwise ones don't benefit from short-circuit evaluation.

**Comment by terzerm** [comment]
Hi, and thanks for your question.
There is no real strong reason, but the idea was that these operations can be better optimised by the compiler, so they may result in marginally better performance.  
See for instance here for an explanation:
https://en.wikipedia.org/wiki/Short-circuit_evaluation#Reduced_efficiency_due_to_constraining_optimizations
