### ISSUE TITLE
Multiplication for zero GC API

### ISSUE THREAD

**Issue by cwengc** [tools4j/decimal4j#23]
Is there a good way to handle multiplication for numbers with the same scale in the most efficient manner possible?

**Comment by terzerm** [comment]
Hi, thanks for your question.

> Is there a good way to handle multiplication for numbers with the same scale …

It depends a bit what you want exactly.  If you multiply 2 numbers with scale d, the result has scale 2d in the general case.  Is that what you want?  By default decimal4j returns a result in the same scale as the first operand, that would be d here, and rounding or truncation may be required.

> … in the most efficient manner possible?

Again depends a bit what you mean with this.  Do you want a zero GC method, or just a convenient way to do it?

For an example for exact multiplication with result 2d scale check the multiplyExact() metods on the DenimslXf  or MutableDecimalXf classes, where X is the scale.  This however is not GC free.

For multiplication with result scale d and rounding or truncation, just use one of the multiply methods, here the MutableDecimal version will not allocate objects if you reuse it multiple times
